[buildPlans.hiosevka]
family = "hIosekva"
spacing = "term"
serifs = "sans"

[buildPlans.hiosevka.ligations]
inherits = "haskell"
enables = [
  "brst",           # (* *)
  "slash-asterisk", # /* */
  # disable <= =< >= completely (no arrows or comparison ligatures)
  "lteq-separate",
  "eqlt-separate",
  "gteq-separate",
]
disables = [
  # never enable comparison ligatures
  "lteq",    # <=
  "gteq",    # >=
  "slasheq", # /=
]

[buildPlans.hiosevka.variants.design]
capital-z = 'straight-serifless-with-crossbar'
capital-q = 'crossing'
lower-lambda = 'tailed-turn'
seven = 'straight-serifless-crossbar'
number-sign = 'slanted'
ampersand = "et-tailed"
dollar = 'open'
cent = "open"
percent = 'rings-continuous-slash-also-connected'
# explicitly declare with-notch
lig-equal-chain = 'with-notch'
lig-hyphen-chain = 'with-notch'
lig-plus-chain = 'with-notch'
lig-double-arrow-bar = 'with-notch'
lig-single-arrow-bar = 'with-notch'

[buildPlans.hiosevka.variants.italic]
v = "cursive-serifless"
w = "cursive-serifless"
