format = """
$hostname$directory$python
$character
"""
right_format = "$git_branch$git_commit$git_state$git_status"

[hostname]
ssh_only = true
format = "[$hostname](bold #fc813a):"
disabled = false

[character]
success_symbol = "[⮑ ](white)"
error_symbol = "[⮑ ](bold red)"

[directory]
truncation_length = 0
truncation_symbol = "…/"
truncate_to_repo = false
style = "bold #d7d7ff"

[git_branch]
symbol = ""
format = "$symbol$branch"

[git_status]
style = "white"

[python]
format = "$virtualenv"