format = """
$hostname$directory$python
$character
"""
right_format = "$git_branch$git_commit$git_state$git_status"

[hostname]
disabled = false
ssh_only = true
style = "bold #ff5f00"
format = "[$hostname]($style):"

[character]
success_symbol = "[⮑](#aaaaaa) "
error_symbol = "[⮑](#c82829) "

[directory]
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo = false
read_only = " "
read_only_style = "#c82829"
style = "black"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_commit]
style = "#875fff"
format = "[\\($hash$tag\\)]($style)"

[git_branch]
symbol = ""
style = "#aaaaaa"
format = "[$symbol$branch]($style)"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
style = "bold #875fff"
format = "([\\[$all_status$ahead_behind\\]]($style))"

[python]
style = "white"
format = "([\\($virtualenv\\)]($style))"
