format = '''
$hostname$directory$python
$character
'''
right_format = '$cmd_duration$git_state$git_branch$git_commit$git_status'

palette = 'lilac'

[palettes.lilac]
lilac = '#875fff'
orange = '#ff5f00'
grey = '#aaaaaa'
crimson = '#c82829'

[hostname]
ssh_only = true
style = 'bold orange'
format = '[$hostname]($style):'

[character]
success_symbol = '[⮑ ](grey)'
error_symbol = '[⮑ ](crimson)'

[directory]
truncation_length = 4
truncate_to_repo = false
style = 'black'
format = '[$path]($style)( [$read_only]($read_only_style))'
read_only = ''
read_only_style = 'crimson'
truncation_symbol = '…/'

[python]
style = 'grey'
format = '( [\($virtualenv\)]($style))'

[cmd_duration]
min_time = 5_000
show_milliseconds = true
format = '([$duration]($style) )'

[git_state]
style = 'bold red'
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_branch]
symbol = ''
style = 'grey'
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_commit]
style = 'lilac'
format = '[\(](grey)[$hash$tag]($style)[\)](grey)'

[git_status]
ahead = '⇡$count'
behind = '⇣$count'
diverged = '⇕⇡$ahead_count⇣$behind_count'
style = 'bold lilac'
format = '([\[](grey)[$all_status$ahead_behind]($style)[\]](grey))'
