format = """
$hostname$directory$python
$character
"""
right_format = "$git_branch$git_commit$git_state$git_status"

[hostname]
disabled = false
ssh_only = true
style = "bold #fc813a"
format = "[$hostname]($style):"

[character]
success_symbol = "[⮑ ](white)"
error_symbol = "[⮑ ](bold red)"

[directory]
truncation_length = 0
truncation_symbol = "…/"
truncate_to_repo = false
read_only = " "
read_only_style = "bold red"
style = "bold #d7d7ff"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_commit]
style = "white"
format = "[\\($hash$tag\\)]($style) "

[git_branch]
symbol = ""
style = "white"
format = "[$symbol$branch]($style) "

[git_status]
style = "#d7d7ff"
format = "([\\[$all_status$ahead_behind\\]]($style) )"

[python]
style = "white"
format = "[\\($virtualenv\\)]($style)"