[buildPlans.altiosevka]
family = "iosevka"
spacing = "term"
serifs = "sans"
noLigation = true

[buildPlans.altiosevka.variants.design]
capital-z = 'straight-serifless-with-crossbar'
capital-q = 'crossing'
lower-lambda = 'tailed-turn'
seven = 'straight-serifless-crossbar'
number-sign = 'slanted'
ampersand = "et-tailed"
dollar = 'open'
cent = "open"
percent = 'rings-continuous-slash-also-connected'
at = "fourfold"
# explicitly declare with-notch
lig-equal-chain = 'with-notch'
lig-hyphen-chain = 'with-notch'
lig-plus-chain = 'with-notch'
lig-double-arrow-bar = 'with-notch'
lig-single-arrow-bar = 'with-notch'
