require "packer-cfg"

require "keymap"
require "options"

require "nvim-cmp-cfg"
require "comment-cfg"
require "gitsigns-cfg"
require "indent-blankline-cfg"
require "telescope-cfg"
require "nvim-autopairs-cfg"
require "nvim-colorizer-cfg"
require "barbar-cfg"
require "todo-comments-cfg"
require "trailing-whitespace-cfg"
require "symbols-outline-cfg"
require "surround-cfg"
require "presence-cfg"
require "auto-dark-mode-cfg"
require "fugitive-cfg"
require "undotree-cfg"
require "diffview-cfg"
require "treesitter-cfg"
require "treesitter-context-cfg"
require "iswap-cfg"
-- require "lualine-cfg"
-- require "startup-cfg"
-- require "toggleterm-cfg"

require "neodev-cfg"
require "lsp-cfg"
require "fidget-cfg"
