require "keymap"
require "options"

require "packer-cfg"

require "treesitter-cfg"
require "nvim-cmp-cfg"
require "comment-cfg"
require "gitsigns-cfg"
require "indent-blankline-cfg"
require "lualine-cfg"
require "telescope-cfg"
require "nvim-tree-cfg"
require "startup-cfg"
require "nvim-autopairs-cfg"
require "nvim-colorizer-cfg"
require "barbar-cfg"
require "toggleterm-cfg"
require "todo-comments"

require "mason-cfg"
require "lsp-cfg"
require "fidget-cfg"
require "neodev-cfg"
