[[language]]
name = "toml"
language-server = { command = "", args = [] }

[[language]]
name = "rust"
auto-format = false
language-server = { command = "rustup", args = [
  "run",
  "stable",
  "rust-analyzer",
] }

[[language]]
name = "markdown"
language-server = { command = "ltex-ls" }
