name: "Cachix"

on:
  push:
    branches: [ main ]

jobs:
  build-packages:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest # M1
          - macos-13 # not m1
        package:
          - altiosevka
          - hiosevka
          - hiosevka-nerd-font-mono
          # - hiosevka-nerd-font-propo # not really used
          - logisim-evolution
          - maeel
          - necrolib
          - tokei
          - why3

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: leana8959
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build '.#${{ matrix.package }}' -L --accept-flake-config
