name: "Cachix"

on:
  push:
    branches: [ mistress ]

jobs:

  #################################################
  # Fonts related (they take 2h to build on a i5) #
  #################################################
  # base iosevka variants
  build-iosevka-variants:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest # M1
          - macos-13 # not m1
        package:
          - altiosevka
          - hiosevka
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/cachix-action@v15
      with:
        name: leana8959
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build '.#${{ matrix.package }}' -L --accept-flake-config

  build-nerd-font-patched-iosevka:
    needs: build-iosevka-variants
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest # M1
          - macos-13 # not m1
        package:
          - hiosevka-nerd-font-mono
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/cachix-action@v15
      with:
        name: leana8959
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build '.#${{ matrix.package }}' -L --accept-flake-config


  ##################
  # Other packages #
  ##################
  linux-packages:
    strategy:
      matrix:
        package:
          - isabelle-wrapped # takes a while to build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/cachix-action@v15
      with:
        name: leana8959
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build '.#${{ matrix.package }}' -L --accept-flake-config
